### ISSUE TITLE
modify megolm's `prepareToEncrypt` to be cancellable

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-js-sdk#1255]
`prepareToEncrypt` is introduced in https://github.com/matrix-org/matrix-js-sdk/pull/1252 so that applications can pre-send keys to recipients before the message itself is ready to send, reducing the amount of work that needs to be done when the message is sent.

However, the current function cannot be cancelled if the key cannot be used after all (e.g. a user/device has left, so the key needs to be rotated).

**Comment by clarkf** [comment]
I believe this is the root cause of vector-im/element-web#21612. Or, well, sorta. Mind if I take a stab at it?

[`MegolmEncryption#prepareToEncrypt`][prepareToEncrypt] does a bunch of expensive, blocking crypto on the main thread per untrusted device (see [`CrossSigningInfo#checkDeviceTrust`][checkDeviceTrust]). I don't think a simple cancellation callback will work, since it mostly blocks the caller.

The most straightforward option would be to break the work up into chunks, wrapped in [`setImmediate`](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) (or similar). Allow preemption between each `checkDeviceTrust` call. Then, cancellation could be added, and vector-im/element-web#21612 resolved (probably).

The "correct" solution would probably be to move the expensive crypto off the main thread, using a WebWorker or something. I don't think that's super reasonable, though, and would require some really sweeping changes.

[prepareToEncrypt]: https://github.com/matrix-org/matrix-js-sdk/blob/c3d422f5fb1efac400da4c4ade592db3831445f9/src/crypto/algorithms/megolm.ts#L944-L989
[checkDeviceTrust]: https://github.com/matrix-org/matrix-js-sdk/blob/c3d422f5fb1efac400da4c4ade592db3831445f9/src/crypto/CrossSigning.ts#L519-L555
