### ISSUE TITLE
[Question] How can we implement pagination for previous chat?

### ISSUE THREAD

**Issue by sushantBansal** [matrix-org/matrix-js-sdk#1564]
I was creating a chat server using matrix chat in node and angular. For this, I am using matrix-js-SDK. The complete setup is complete but the only issue is to get the previous chat as I logged in with credentials I got the last 5-8 chat messages. 

I have read in docs something about pagination but couldn't find any proper documentation regarding the same. 

If you could help me with this. This would be much appreciated.

**Comment by menturion** [comment]
@sushantBansal 

Have a look at method `MatrixClient.prototype.paginateEventTimeline`. 

Or even better suited for dealing with replies (see `ev.getWireContent()['m.relates_to']` and `m.in_reply_to`) by instantiating a `TimelineWindow` and then using methods `TimelineWindow.prototype.load` and `TimelineWindow.prototype.paginate`.

**Comment by jryans** [comment]
For future questions, we recommend asking in Matrix rooms.

**Comment by menturion** [comment]
@jryans 

People ask their questions here on Github because the questions are often not answered in the Matrix rooms.

Furthermore, Matrix rooms are not a suited medium to discuss such problems. Here on Github, you have a ...

- contiguous 
- problem related and 
- thread based 

... discussion. 

Existing issues can be easily found using the Github and public search engines like Google et al. Related issues can be conveniently referenced. ... All this isn't possible in Matrix rooms.
 
It would be to Matrix's advantage to build a knowledge base here on Github instead of referring users to the Matrix rooms.
