### ISSUE TITLE
No sound played on client when using placeVoiceCall()

### ISSUE THREAD

**Issue by nahakiole** [matrix-org/matrix-js-sdk#2088]
**Describe the bug**
When I use the following code to place a call, I can't hear the other person in my client. 
```typescript
let matrixCall = sdk.createNewMatrixCall(
    this.mx.client, room.roomId
);

matrixCall.placeVoiceCall();
```
The other client in the elementor client can hear me however.

**To Reproduce**
1. Create a new matrix-js-sdk Project
2. Initialize the client
3. Call someone from the client with the above code
4. You can't hear them, but they can hear you.

**Expected behavior**
I'd like to hear the other person or know how I can set the audio output.

In this article there was a method `setRemoteAudioElement` which has since been removed. Is there a new way to set the audio element?
```
matrixCall.setRemoteAudioElement(document.getElementById("remote-audio"));
```
https://howto.lintel.in/voip-matrix-js-sdk/

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome 
 - Version 96.0.4664.110

**Comment by SimonBrandner** [comment]
I would suggest you try out [the VoIP example ](https://github.com/SimonBrandner/matrix-js-sdk/tree/fix/voip-example-device-id/examples/voip) (linking to my fork as it has a fix for https://github.com/matrix-org/matrix-js-sdk/issues/2083 which isn't upstream yet) and visit https://matrix.to/#/#matrix-dev:matrix.org if you have any questions. The article really is outdated and the example shows how this should be done now

**Comment by nahakiole** [comment]
I think this should be left open until it's properly documented. Also it's not logical that I need a video element to make a voice call. That's also not documented at all. I can create a pull request and update the documentation.

Also from experience the documentation could use more examples. I'm currently working with another person on my bachelor using matrix and maybe we'll be able to contribute some time to improve the documentation.

I've actually asked the question on the official channel, but it seems to be dead?
 https://matrix.to/#/#matrix-js-sdk:matrix.org

**Comment by SimonBrandner** [comment]
> ​I think this should be left open until it's properly documented.

I would suggest opening a new issue asking for better VoIP documentation as that is better for the organization of things. This issue seems to be reporting a bug that actually isn't a bug. Therefore a new issue describing the problems of the VoIP documentation linking to this one (as an example of the confusion caused by imperfect documentation) would be better.

> Also it's not logical that I need a video element to make a voice call. 

You can change the `video` element to an `audio` element and change `placeVideoCall()` to `placeVoiceCall()` to have a voice call instead. Hopefully, that should work

> That's also not documented at all. I can create a pull request and update the documentation and at least link the example in the API documentation.
> Also from experience the documentation could use more examples. I'm currently working with another person on my bachelor using matrix and maybe we'll be able to contribute some time to improve the documentation.

Yes, the documentation isn't perfect, we're aware of that. Contributions are always welcome!

> I've actually asked the question on the official channel, but it seems to be dead? [matrix.to/#/#matrix-js-sdk:matrix.org](https://matrix.to/#/#matrix-js-sdk:matrix.org)

The right people always aren't around, feel free to repeat the questions after a reasonable delay if you got no answer. Also, when it comes to VoIP feel free to ping me (`@simon.brandner:envs.net`)

**Comment by SimonBrandner** [comment]
> but it seems to be dead?

That room seems to be unofficial and dead, yes
