### ISSUE TITLE
Use ruma to parse and verify (API) types

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-js-sdk#2117]
Currently, in a lot of spots on the SDK, API returns are simply *assumed* readily typed, this could become a problem if the server misbehaves or does not respond correctly.

To make js-sdk more resilient, I think it could help if the rigorous parsing and checking of [ruma](https://www.ruma.io/docs/crates/ruma-client-api/) could be used, with which it results in an succeed-or-error scenario, allowing the SDK to handle these "wrong" situations better.

This may also apply in other areas of matrix, where certain type-checking would help a long way with verifying the data returned is actual and well-formed.

**Comment by turt2live** [comment]
Bringing in that much of Ruma means ditching javascript entirely, which is not ideal for this project. We should be putting more validation on things, but traditionally we assume we are talking to a well-behaved server because, well, we should be. 

Closing as an unlikely path we'll take. If we do want to take this path down the line, I think it'll be best tracked outside of the issue tracker.
