### ISSUE TITLE
Make docs easier to search

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-js-sdk#265]
It would be nice to provide an easy way to search for relevant functions instead of relying on the user clicking the right link and then doing <kbd>ctrl+f</kbd>.

**Comment by select** [comment]
I build an index for the matrix client, maybe this helps you too https://github.com/matrix-org/matrix-js-sdk/issues/608#issuecomment-420809608

**Comment by Ryuno-Ki** [comment]
Since the docs get generated with JSDocs, I can only imagine putting a search engine on top of it by means of Google Custom Search Engine or Algolia.

Here's what CSS-Tricks did to make it work (with WordPress):
* https://css-tricks.com/on-site-search/ about setting it up
* https://css-tricks.com/fast-good-local-site-search-with-jetpack/ about dropping it

This will likely not be an easy fix.

**Comment by Johennes** [comment]
![Screenshot 2023-11-13 at 14 31 43](https://github.com/matrix-org/matrix-js-sdk/assets/1137962/dd70ab0e-4ec1-451c-baf1-7fe51a5c5c1e)

This appears to be a non-issue these days.
