### ISSUE TITLE
Remove verbose logging from files in src/crypto

### ISSUE THREAD

**Issue by merisbahti** [matrix-org/matrix-js-sdk#332]
In order to not clutter the console for people who are developing using this SDK, perhaps we should remove the most verbose logging which comes up when using crypto?

(An alternative would be to use some logging library, such as the ones recommended in [this post](https://blog.risingstack.com/node-js-logging-tutorial/))

These are the relevant lines that I could find:

`src/crypto/algorithms/megolm.js`:
 * [#L68](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/algorithms/megolm.js#L68)
 * [#L96](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/algorithms/megolm.js#L96)

`src/crypto/algorithms/olm.js`:
 * [#L256](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/algorithms/olm.js#L256)
 * [#L311](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/algorithms/olm.js#L311)

`src/crypto/olmlib.js`:
 *   [#L65](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/olmlib.js#L65)
 *   [#L229](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/olmlib.js#L229)

`src/crypto/index.js`:
 * [#L356](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/index.js#L356)
 *  [#L390](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/index.js#L390)

`src/crypto/OlmDevice.js`:
 * [#L655](https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/crypto/OlmDevice.js#L655)

**Comment by Ryuno-Ki** [comment]
I'd take a stab at this, since I encountered in [sync.js](https://github.com/matrix-org/matrix-js-sdk/blob/5d84db9fb72678af38c50de5eefe4c0b7bd48af1/src/sync.js).

My personal favourite regarding logging is [loglevel](https://www.npmjs.com/package/loglevel), because it's API is quite simple and it works everywhere (as compared against winston, which is tailored to Node.js) and it supports plugins (for timestamp or submission to a server).

Debug is nice also.

@dbkr Any preferences?
Would you accept a PR? I've read [CONTRIBUTION.rst](https://github.com/matrix-org/matrix-js-sdk/blob/5d84db9fb72678af38c50de5eefe4c0b7bd48af1/CONTRIBUTING.rst) already.

**Comment by dbkr** [comment]
Yeah, the logging is vital for debugging crypto but it would be nice to be able to turn it off somehow. loglevel looks very sensible - if you wanted to make a PR that would be great!

**Comment by Ryuno-Ki** [comment]
Opened #763 to address the issues of the original request.

**Comment by Ryuno-Ki** [comment]
@dbkr Can we close this? The PR was accepted.
