### ISSUE TITLE
"You don't have access to this message"

### ISSUE THREAD

**Issue by jeffrson** [matrix-org/matrix-js-sdk#4402]
We have a room, which from the very beginning was configured to make future room history visible to all room members.

When I was invited to this room months ago, messages of most people were visible to me. For one person, however, every message was (and in fact still is) shown as "You don't have access to this message" with a key icon and tooltip "This message could not be decrypted". The raw message says

> ** Unable to decrypt: DecryptionError: This message was sent when we were not a member of the room. **

This is apparently until I really joined the room. So why could I see most person's messages, but not those of this particular person?
And why does this error happen at all, despite the setting of making history available to all room members?

Now I invited another colleague to this room. He cannot see any of the messages but "You don't have access to this message" for all of them. Is there any way to fix this?

We use synapse v1.114.0 and element-web v1.11.77.

PS: in Element for Android the messages are shown as "Waiting for this message. This could take a while." - may not be exact, since I translated it from a non-english locale.

**Comment by richvdh** [comment]
It is expected that you are unable to see history that was sent while you were not a member of a room; work to improve this is tracked at https://github.com/element-hq/element-meta/issues/749#issuecomment-2263750966, but is not currently a priority.

Previously, there was some support for sharing history when you received an invite, but it was removed, mostly due to security concerns. It sounds like you can see most messages due to that support, but also found a bug in the implementation which meant you can't decrypt one specific user.

The message in Element Android is misleading, but since EA is now in maintenance mode, it's unlikely that it will be changed.

In future, it's best to open issues against the application you're using (element-web), rather than the js-sdk.

**Comment by mogul** [comment]
> since EA is now in maintenance mode

Sorry, can I find out more about this!? It's news to me.
