### ISSUE TITLE
startClient with await

### ISSUE THREAD

**Issue by grigori-gru** [matrix-org/matrix-js-sdk#789]
Hello!

We use this project for 1.5 years with our [jira-bot](https://github.com/mobitel-ltd/jira-to-matrix). I've seen that you added startClient with async. Maybe I don't understand your idea but it still don't work as I need, for example if we use it like this:
```js
async () => {
  const client = sdk.createClient({baseUrl, accessToken, userId});
  await client.startClient({lazyLoadMembers: true});
  return client;
}
```
If you check `client ` sync state it will be null. We are obliged to warp it into Promise with event waiting for working sync state inside. It's something like this after:

```js
return new Promise((resolve) => {
   client.on('sync', (state) => {
      if (state === 'SYNCING') {
         resolve(client);
       }
   });
  });
```

Is it what you expect to do? Or there is some other way to do this - get working state after finish startClient async function?

**Comment by bwindels** [comment]
Hi @grigori-gru 

We made `startClient` return a promise in `0.11.0` because it needed to check server support for member lazy loading before starting to sync. Later on it was [brought to our attention](https://github.com/vector-im/riot-web/issues/7455) that doing it like that prevents restoring the session when the HS is unreachable, thus breaking off-line usage, so now this check happens as part of the first sync, making the Promise not entirely necessary any more. We've decided to keep the API as it is though, to prevent another breaking change, and in the future we might need to do more async things within `startClient`.

The design is probably not ideal. Sorry this has complicated stuff for SDK users like yourself. I would suggest to combine the promises, something like so:

```javascript
async function createSyncingClient(baseUrl, accessToken, userId) {
	const client = sdk.createClient({baseUrl, accessToken, userId});
  	const startClientPromise = client.startClient({lazyLoadMembers: true});
	const syncPromise = new Promise((resolve, reject) => {
		client.on('sync', (state, payload) => {
			if (state === 'SYNCING') {
				resolve(client);
			} else if (state === 'ERROR'){
				reject(payload.error);
			}
		});
	});
	await Promise.all([startClientPromise, syncPromise]);
	return client;
}
```

Please reopen if you have further questions.
