### ISSUE TITLE
Consider switching http libs

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-js-sdk#801]
something like https://github.com/visionmedia/superagent works nicely in both the browser and in node. `request` does work in both, but is painful and large for the browser (and causes weird problems sometimes).

**Comment by turt2live** [comment]
Related: https://github.com/matrix-org/matrix-js-sdk/issues/244

**Comment by turt2live** [comment]
Replacing `request` would be a huge undertaking as the js-sdk and its consumers make a huge number of assumptions about the library being used. We'd almost certainly need to cut a major release, although that's not impossible.

Most of the HTTP code should be in one place, with the exception of all the places that rely on the response/error objects from `request`. Riot would also need to make use of the new library.

The shorter answer is that I unfortunately don't have a list, but I do know it is a long one.

**Comment by stalniy** [comment]
I would recommend to use [axios](https://github.com/axios/axios). [request is maintance mode](https://github.com/request/request/issues/3142)

> The most valuable thing request can do for the JavaScript ecosystem is to go into maintenance mode and stop considering new features or major releases

**Comment by jonassmedegaard** [comment]
Maybe this feature comparison is helpful in deciding which alternative to switch to: https://github.com/sindresorhus/got#comparison

**Comment by jc-delvalle** [comment]
I was having some issues login in with JWT token and request. 

I ended up doing this: 
`const client = sdk.createClient({
      baseUrl: 'https://matrix-dev.mydomain.com',
      request: async function (opts, fn) {                                                                                                        
        opts.url = opts.uri;  
        opts.data = opts.body;  
        const res = await axios(opts);  
        fn(null, res, JSON.stringify(res.data));  
      },  
    });`

Since I was not able to make this endpoint work with request in any way, I even tried isolated tests and I always received  'Error: Server returned 403 error' until I switched to axios, this endpoint is working with browser-request.

Since it seems like a very simple change in interface from request to axios, is there any effort already going on switching into another library?

I would love to contribute to this if you think this is the right approach.

**Comment by t3chguy** [comment]
There is a WIP PR to move over to fetch, which is a more likely candidate as it is built-in in the web

**Comment by jc-delvalle** [comment]
Great! Thanks.

**Comment by bradjones1** [comment]
This is the aforementioned PR, though it is 4 years old now: https://github.com/matrix-org/matrix-js-sdk/pull/797

**Comment by bradjones1** [comment]
Not sure if this helps in evaluation, but I had a use case to use Fetch with the current SDK; here's a gist of my wrapped implementation that supports aborting. Seems to work... so far?

https://gist.github.com/bradjones1/dae3207aa7dce6eb508cfec56a76ae99

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/22265 which has had recent push to be part of the 2022 tech strategy.

**Comment by t3chguy** [comment]
@MadLittleMods given that element-web is not the only consumer of the js-sdk, this is a far better place to collect opinions from other consumers

**Comment by t3chguy** [comment]
Keeping Enhancement due to it adding new features

- We won't be depending on an unmaintained library
- We think this will allow us to upload files without loading them into memory, as [File](https://developer.mozilla.org/en-US/docs/Web/API/File) objects can be passed as a Blob in the [body option of a Request](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) rather than having to load blob data into a buffer as is currently done
- We could use the [priority option](https://developer.mozilla.org/en-US/docs/Web/API/Request/priority) to make some requests more important than others

**Comment by t3chguy** [comment]
Current thinking is to switch to fetch, for js-sdk it'll still need a polyfill given the Node version where fetch support was added is more modern than our minimum supported version

**Comment by 3nprob** [comment]
Not sure if OT for this topic or not but it'd be great if the replacing lib either has or is easy to extend with reasonable (exponential backoffs) retry behavior. I think this has the potential to improve UX greatly in scenarios with unreliable or intermittent HS connectivity.

The `fetch` API has the obvious benefit of being native and could be wrapped with something like [@adobe/node-fetch-retry](https://www.npmjs.com/package/@adobe/node-fetch-retry). Note that as of v18, nodeJS native fetch functionality is provided by [`undici`](https://github.com/nodejs/undici), which has some subtle differences compared with `node-fetch` so using that instead of `node-fetch` will minimize behavioral differences between node versions while leveraging the native API when possible.

It could also be worth considering options like [`ky`](https://github.com/sindresorhus/ky-universal). Made by the people behind [`got`](https://github.com/sindresorhus/got). When trying and benchmarking the `request` alternatives for a backend-only use-case a while back, `got` was a hands-down winner for several reasons and it's been great since.

Since axios was mentioned: Even if axios is popular and looks great at first glance we had so many tricky-to-debug issues and edge-cases with it over the years, some are still open. I really would not recommend it today.

**Comment by t3chguy** [comment]
> easy to extend with reasonable (exponential backoffs) retry behavior.

Retry behaviour is rarely easy, given that even if the response failed to make it to the requester, the effect may have taken place, so really you can only retry GET and PUTs which are idempotent via txnId

**Comment by 3nprob** [comment]
> > easy to extend with reasonable (exponential backoffs) retry behavior.
> 
> Retry behaviour is rarely easy, given that even if the response failed to make it to the requester, the effect may have taken place, so really you can only retry GET and PUTs which are idempotent via txnId

Depends. Common practice is to differentiate between error codes, where e.g. a `429` is considered safe to retry but a timeout is not.

**Comment by t3chguy** [comment]
408 Request Timeout doesn't feel safe to retry, the server may have received the request successfully here and acted upon it.

---

502 Bad Gateway doesn't feel safe to retry, given it is specified as 

> the server, while acting as a gateway or proxy, received an invalid response from the upstream server.

Not that the upstream server wasn't given the request

---

504 Gateway Timeout is certainly not safe to retry, in this case the upstream server more than likely got the request, but the response will never make it back to the caller.

**Comment by 3nprob** [comment]
Honestly even limiting to just idempotent GETs would still cover all instances I can recall where this forced me to restart the application so I still think that's a win.
